Refactor to use the Docksal cli container to service the web requests.

diff --git a/.docksal/services/wagtail/Dockerfile b/.docksal/services/wagtail/Dockerfile
--- a/.docksal/services/wagtail/Dockerfile
+++ b/.docksal/services/wagtail/Dockerfile
@@ -1,33 +1,25 @@
-ARG PYTHON_IMAGE
+ARG CLI_IMAGE
 
-FROM ${PYTHON_IMAGE}
+FROM ${CLI_IMAGE}
 
-ENV PYTHONUNBUFFERED 1
-ENV PYTHONDONTWRITEBYTECODE 1
+# Install additional apt packages
+RUN set -xe; \
+    apt-get update >/dev/null; \
+    apt-get -y --no-install-recommends install >/dev/null \
+    postgresql-client \
+    pipx \
+    python3.poetry \
+    # Cleanup
+    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
-# Install system packages required by Wagtail and Django.
-# https://github.com/wagtail/wagtail/blob/v4.0.2/wagtail/project_template/Dockerfile
-RUN apt-get update --yes --quiet \
-&& apt-get install --yes --quiet --no-install-recommends \
-    build-essential \
-    libpq-dev \
-    libmariadbclient-dev \
-    libjpeg62-turbo-dev \
-    zlib1g-dev \
-    libwebp-dev \
-    msmtp \
-    curl \
- && rm -rf /var/lib/apt/lists/* \
- # From https://github.com/python-poetry/poetry
- && curl -sSL https://install.python-poetry.org/ | python
+# Install base python libraries.
+COPY ./base/pyproject.toml /pyproject.toml
+COPY ./base/poetry.lock /poetry.lock
+RUN /usr/bin/poetry install
 
-# Requirements are installed here to ensure they will be cached.
-COPY ./pyproject.toml /pyproject.toml
-COPY ./poetry.lock /poetry.lock
-RUN /root/.local/bin/poetry install
 ENV _PYTHON_VERSION=3.11
 # ENV _PYTHON_VENV_PATH=`eval /root/.local/bin/poetry env info --path`
-ENV _PYTHON_VENV_PATH=/root/.cache/pypoetry/virtualenvs/wagtail-app-il7asoJj-py$_PYTHON_VERSION
+ENV _PYTHON_VENV_PATH=/home/docker/.cache/pypoetry/virtualenvs/wagtail-app-p9HyaoIY-py$_PYTHON_VERSION
 ENV PYTHONPATH=$_PYTHON_VENV_PATH/lib/python$_PYTHON_VERSION/site-packages
 
 COPY ./services/wagtail/entrypoint /entrypoint
@@ -40,7 +32,6 @@ RUN chmod +x /start
 
 EXPOSE 8000
 
-WORKDIR /app
+WORKDIR /var/www/${DOCROOT}
 
 ENTRYPOINT ["/entrypoint"]
-
